sudo: required
services:
  - docker
env:
  global:
    # set a useful / unique (for the commit) SHA to tag images with
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # encrypted keys (by travis ci) from google cloud
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in docker-k8s-multi-container-922bb889d5f2.json.enc -out docker-k8s-multi-container-922bb889d5f2.json -d
  # download googles cloud sdk and install it (don't show the output)
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # service account system ~~ aws IAM system
  - gcloud auth activate-service-account --key-file docker-k8s-multi-container-922bb889d5f2.json
  - gcloud config set project docker-k8s-multi-container
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials cluster-1
  # log into docker - works because docker is specified as a service above
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t nick3141/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nick3141/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master