apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    # tell kubernetes we want an ingress controller based on nginx
    kubernetes.io/ingress.class: nginx
    # remove /api/ when rerouting to the api server
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - datachron.org
        - www.datachron.org
      secretName: datachron-org
  rules:
    - host: datachron.org
      http:
        paths:
          # route non default paths to the client
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          # route /api/ paths to the api cluster ip service (api deployment)
          - path: /api/
            backend:
              serviceName: api-cluster-ip-service
              servicePort: 5000
    - host: www.datachron.org
      http:
        paths:
          # route non default paths to the client
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          # route /api/ paths to the api cluster ip service (api deployment)
          - path: /api/
            backend:
              serviceName: api-cluster-ip-service
              servicePort: 5000
